// ACTION CONSTANTS FOR AUTHORIZATION
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const SAME_PASS_ERROR = 'SAME_PASS_ERROR';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

// ACTION CONSTANTS FOR TODOLIST
export const ADD_UID =  'ADD_UID';
export const ADD_TODO_LIST = 'ADD_TODO_LIST';
export const LOGGIN_OUT = 'LOGGIN_OUT';
export const UPDATE_TODO_LIST = 'UPDATE_TODO_LIST';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const UPDATE_FILTER = 'UPDATE_FILTER';
